a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type (a))
print('Só tem espaços? ', a.isspace())
print('é um número? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('É alfanumérico', a.isalnum())
print('É maiusculo? ', a.isupper())
print('É minusculo? ', a.islower())
print('É estilizado', a.istitle())